language: objective-c
osx_image: xcode9.3

xcode_workspace: "3 Apps in 3 Hours.xcworkspace"

cache:
  - bundler
  
before_install:
  - gem install bundler
  - bundle install

script:
  - ./Scripts/build.sh
  